### ISSUE TITLE
Incorrect version requirements for dependencies in fabric.mod.json

### ISSUE THREAD

**Issue by Exopandora** [Fuzss/forgeconfigapiport-fabric#11]
The fabric.mod.json for v3.2.2 (~~and possibly other versions~~ applies to all recently released versions) contain the wrong version numbers for the required libraries included in the fabric api. When trying to launch the game with fabric-api 0.47.8 it will result in the following error:

```
 net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install fabric-command-api-v2, version 0.47.8 or later.
Unmet dependency listing:
	 - Mod 'Forge Config API Port' (forgeconfigapiport) 3.2.2 requires version 0.47.8 or later of fabric-command-api-v2, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148) ~[fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.8.jar:?]
	at net.fabricmc.devlaunchinjector.Main.main(Main.java:86) [dev-launch-injector-0.2.1+build.8.jar:?]
```

The actual required version of fabric-command-api-v2 should be 1.1.8

**Comment by Exopandora** [comment]
This also applies to fabric-lifecycle-events-v1 and fabric-networking-api-v1

**Comment by Fuzss** [comment]
v3.2.1 is broken unfortunately, v3.2.2 works fine for me though, couldn't get it to show that error you got.

I released new versions though which have no minuten version of Fabric Api set anymore, so hopefully that'll work for you. Saw Mod Menu does it like that, so hopefully there really won't be any issues.

**Comment by Exopandora** [comment]
Yes modmenu does it, but it sets the correct version in the fabric.mods.json. But each api-jar (i.e. fabric-lifecycle-events-v1) has its own version which does not equal the fabric-api version.

**Comment by Exopandora** [comment]
Works now, thanks!
