### ISSUE TITLE
Crashes on fabric 0.14.8-1.19

### ISSUE THREAD

**Issue by InfidelKilla** [Fuzss/forgeconfigapiport-fabric#12]
Crashes on startup with exit code 1. Using fabric 0.14.8-1.19  I don't know whats causing this crash because it worked fine in a previous version of fabric of mc 1.19. 
![image_2022-08-03_143850716](https://user-images.githubusercontent.com/91441433/182684548-e6c08fea-de98-4427-ba6d-241f6b003d72.png)

**Comment by Fuzss** [comment]
Please post your crash-report so I can help you. 

https://gist.github.com/Fuzss/9692f6ed5e8cca485a58004c28c9045b

**Comment by ingmarSimonse** [comment]
Same problem, previous version of forge config api works. there is no crash-report

**Comment by Fuzss** [comment]
There is a `latest.log` though, please upload that at least. I need something to go off on.

https://gist.github.com/Fuzss/866b384d353912986e37b17eeef7a285

**Comment by ingmarSimonse** [comment]
https://gist.github.com/ingmarSimonse/fd0db468773cda1431126aa2082065f1

**Comment by Fuzss** [comment]
Looks like one of the 1.19.1 versions was mislabelled as working on 1.19 too which is not the case.

Get the latest 1.19 build [from here](https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric/files/all?filter-status=1&filter-game-version=2020709689%3A9186) and it should work.

**Comment by ingmarSimonse** [comment]
ohh yeah i see, that works. thanks

**Comment by floral-qua-floral** [comment]
Forge Config API Port v4.1.4 is still marked as 1.19 compatible on the [Modrinth](https://modrinth.com/mod/forge-config-api-port/version/4.1.4) page, it'd be nice if it could be corrected there.

**Comment by Fuzss** [comment]
v4.2.2 is now properly compatible and I've fixed the version tags for the old one. Thanks for reporting!
