### ISSUE TITLE
[Bug]: Visual glitch/inconsistency when trading with NPCs

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [Fuzss/forgeconfigapiport-fabric#17]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.0

### Notes (Required)

1. For convenience use creative mode, grab a Wandering Trader egg (can be a Villager too, but it's faster with WT because they don't need workstations), spawn the trader
2. Open the trading menu and click on any few items the trader is offering
3. Notice how the white outline permanently stays on items that you've previously selected
4. To remove the outlines, select those items again

This behavior is inconsistent with vanilla, where the outlines disappear as soon as you choose another item. Looks pretty buggy and confusing. Affects Quilt as well as Fabric.

On this screenshot I clicked through the first 4 items and stopped at Allium (note: you don't have to have emeralds to reproduce this):
![2022-08-21_10 57 44](https://user-images.githubusercontent.com/86702831/185783911-c28801dd-12e4-45f6-94c6-6c485bfa61e4.png)

### latest.log (Optional)

https://gist.github.com/Footage2-Amply-Pounce/d70d5c27edf3c9c606210da5ac9a19fe

**Comment by Fuzss** [comment]
Fixed in v4.2.2, thanks for reporting!
