### ISSUE TITLE
[Crash]: My Fabric launcher won't launch

### ISSUE THREAD

**Issue by TheDeltaTube** [Fuzss/forgeconfigapiport-fabric#18]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.1

### Mod Version (Required)

v4.2.3

### Notes (Required)

I installed both the mod and the sources file. Then, I tried launching it and it crashed. I read the report and it says incompatible so I tried installing another version (4.1.4). Still crashed.

### Crash Report (Required)

https://gist.github.com/TheDeltaTube/6a7da3c51bd7fb24bcdce157c67007b9

**Comment by Fuzss** [comment]
You never install the `-source` file from any mod, that's only for other devs. It's not supposed to work.

Only install the main jar file and everything will be ok.

**Comment by TheDeltaTube** [comment]
Oh, I see. I didn't know that. Thanks for the help
