### ISSUE TITLE
[Suggestion]: Re-add the license headers to all Forge-originated and derived classes.

### ISSUE THREAD

**Issue by TheCurle** [Fuzss/forgeconfigapiport-fabric#19]
### Suggestion (Required)

Context: I am the effective lead developer of Forge, the maintainer of the config system among others.

This mod is great, and i personally think it's a great idea to aid cross-platform compatibility and development of mods.

However, it's licensed under the Mozilla Public License, which is not by default compatible with the LGPL v2.1 that Forge is shipped under.

To make it compatible is easy, however; simply re-add the attribution for our classes, even those you modified.

Some files still have the header; 
```
/*
 * Copyright (c) Forge Development LLC and contributors
 * SPDX-License-Identifier: LGPL-2.1-only
 */
```

But most seem to have it removed.

This advice is derived from [Section 2.c of the LGPL](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.en.html), which states:
```
2. You may modify your copy or copies of the Library or any portion of it, thus forming a work based on the Library, and copy and distribute such modifications or work under the terms of Section 1 above, provided that you also meet all of these conditions: 

[...]

    c) You must cause the whole of the work to be licensed at no charge to all third parties under the terms of this License.
```

This means that the files become valid under the original LGPL license again, which can be combined with your own whole works under MPL and we're back in the legal clear.

Thanks,
Curle

**Comment by Fuzss** [comment]
Hey Curle, thanks a lot for telling me about this issue.

I've now gone through the code and added Forge's license header to all classes copied from Forge. I've also added block comments in those classes whenever a change to Forge's original code has been made.

Please tell me if these additions are enough or if there's anything else you want me to change.

**Comment by TheCurle** [comment]
👍 I can't verify that all classes that need the license have it, so I trust you've done the due diligence here.

That's more or less all it needed. It wasn't a major thing to start with, just something a community member noticed.

Thanks!
