### ISSUE TITLE
[Crash]: Version 4.2.4 causes a crash with The One Probe if Pick Up Notifier is also present

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [Fuzss/forgeconfigapiport-fabric#20]
### Mod Loader (Required)

Quilt

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.4

### Notes (Required)

1. Install Pick Up Notifier 4.2.0 + Forge Config API 4.2.4 + PuzzlesLib 4.2.4 + [The One Probe](https://www.curseforge.com/minecraft/mc-mods/the-one-probe-fabric) 6.2.0
2. Launch the game, create a world, then exit
3. The game crashes on saving world

Logs provided are from my tests on Quilt, but the issue is present on Fabric as well. I've included 3 files, latest.log and crash.log with FCAPI 4.2.4 and latest.log with FCAPI 4.2.3.

Reverting Forge Config API to 4.2.3 solves the issue.

### Crash Report (Required)

https://gist.github.com/Footage2-Amply-Pounce/658f38546bcfd86bd436a8f473b4b318

### latest.log (Optional)

All 3 logs are included in the gist.

**Comment by Fuzss** [comment]
Fixed in v4.2.5.
