### ISSUE TITLE
[Bug]: Fabric not "recognize" the forgeconfigapi jar

### ISSUE THREAD

**Issue by mlengka93** [Fuzss/forgeconfigapiport-fabric#21]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.6

### Notes (Required)

Fabric think i required to - Install forgeconfigapiport_version, version 4.2.6 or later. But i did installed it.

### latest.log (Optional)

https://pastebin.com/DMGbLXFb

**Comment by Fuzss** [comment]
This should be fixed in the latest of Harvest with ease.
