### ISSUE TITLE
[Crash]: Game Crashes without any info when the mod is in the mods folder

### ISSUE THREAD

**Issue by Sackthing2057** [Fuzss/forgeconfigapiport-fabric#22]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.6

### Notes (Required)

I have a lot of mods, the mods of your's I am using are:

Air Hop

Trading Post

Easy Magic

Puzzles Lib

(and of course) Forge Config API Port

### Crash Report (Required)

https://pastebin.com/mtpzMe9A

### latest.log (Optional)

https://pastebin.com/MSmNei4B

**Comment by Sackthing2057** [comment]
sorry i also have pick up notifier

**Comment by Sackthing2057** [comment]
i found out what the problem was and it wasnt your mod. sorry if i may have wasted your time in any shape or form

**Comment by Fuzss** [comment]
All good, no worries!
