### ISSUE TITLE
1.19.2 Fabric crash

### ISSUE THREAD

**Issue by GermanArtur** [Fuzss/forgeconfigapiport-fabric#24]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

4.2.5

### Notes (Required)

1. Open the modlist (mod menu).
2. Find and open modpage one of these mods: stylish effects, trading post.
3. Click the configuration button.
4. Game crashed.

### Crash Report (Required)

https://paste.ee/p/8iqBC

**Comment by Fuzss** [comment]
Please install v4.2.6.
