### ISSUE TITLE
[Crash]: My Game just crashes sometimes randomly and the crash-report says something about this mod

### ISSUE THREAD

**Issue by XMaxinatorX** [Fuzss/forgeconfigapiport-fabric#28]
### Mod Loader (Required)

Fabric

### Minecraft Version (Required)

1.19.2

### Mod Version (Required)

v4.2.7

### Notes (Required)

I am just randomly crashing while playing the game

### Crash Report (Required)

https://gist.github.com/XMaxinatorX/8f90cbb7f24dac2b6534a3fc56704ff0

**Comment by Fuzss** [comment]
The crash-report you posted does not reference this mod. You should contact the author of `me.pepperbell.continuity` instead.
