### ISSUE TITLE
1.19 doen't match latest forge config changes aka missing ConfigValue#getDefault

### ISSUE THREAD

**Issue by AlphaMode** [Fuzss/forgeconfigapiport-fabric#3]

**Comment by Fuzss** [comment]
Thanks for pointing that out!

I'm waiting on [this Forge pr](https://github.com/MinecraftForge/MinecraftForge/pull/8874) to be merged as it brings more changes to the config system, then I'll make sure to sync up all changes.

**Comment by Fuzss** [comment]
Fixed in v4.1.2 for Minecraft 1.19.1.
