### ISSUE TITLE
it has a problem very critical one

### ISSUE THREAD

**Issue by wastaken90** [Fuzss/forgeconfigapiport-fabric#7]
it isnt 1.16.5 fabric.

**Comment by Fuzss** [comment]
That would be correct.

To you need it for a certain project?

**Comment by wastaken90** [comment]
thank you for the reply but i would love it to be 1.16.5 because it would complete my mod collection and when i saw this mod i loved it. so it would be great if u can make it fabric 1.16.5 Thank you. Regards wastaken

**Comment by wastaken90** [comment]
and could you upload it to your main fabric page of this mod thanks.

**Comment by Fuzss** [comment]
Hmm, unless you are working on a mod that needs this sort of library there doesn't seem to be a reason here to make a port.

**Comment by wastaken90** [comment]
can you please make it i really want to run the shoulder surfing mod.

**Comment by wastaken90** [comment]
and i could use it in a mod later on if i want to make one thanks.

**Comment by Fuzss** [comment]
The Shoulder Surfing mod doesn't exist for Fabric on 1.16, Forge Config Api Port isn't magically gonna make it work, that's not what it does...

**Comment by wastaken90** [comment]
hmm. your right

**Comment by wastaken90** [comment]
and by the way do you know any mods like shoulder surfing for fabric 1.16?

**Comment by Fuzss** [comment]
here is a 1.16 port: https://www.curseforge.com/minecraft/mc-mods/forge-config-api-port-fabric/files/3912281

**Comment by wastaken90** [comment]
thx man i got shoulder surfing mod the owner made me the 1.16.5 one
