### ISSUE TITLE
Version 3.2.1 for 1.18.2 requires nonexistent mod ("fabric-command-api-v2")

### ISSUE THREAD

**Issue by raceimaztion** [Fuzss/forgeconfigapiport-fabric#9]
While there _is_ a folder inside the Fabric GitHub repository literally called "fabric-command-api-v2", I cannot find anywhere (including using Google, CurseForge, or Modrinth) an actual release for this mod. It's not even listed under the Relations tab, or the Related Projects section under the File Details for this version.

**Comment by Fuzss** [comment]
Thanks, fixed in v.3.2.2.
